openapi: 3.0.0
info:
  title: Documentation de l'API
  description: API pour voir les tableaux de scores des donjons
  version: 1.0.0

paths:
  /api/players/:
    get:
      parameters:
        - name: page
          in: query
          description: Le numéro de la page
          schema:
            type: integer
            default: 1
          required: false
        - name: size
          in: query
          description: La taille de la page
          schema:
            type: integer
            default: 5
          required: false
      description: Donne la liste des joueurs
      responses:
        '200':
          description: Récupération de la liste des joueurs réussie
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    
    post :
      description: Ajoute un joueur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  uniqueItems: true
      responses:
        '201':
          description: Insertion du nouveau joueur réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
      
        
                    
    